### ISSUE TITLE
Not working again?

### ISSUE THREAD

**Issue by brknkfr** [mathewmeconry/TV7_EPG_Data#12]
Somehow the TV7_EPG_Data is empty or not working anymore. Getting the EPG data with TV7_EPG_Parser manually works ...

**Comment by jokay** [comment]
It seems to have data again?

**Comment by brknkfr** [comment]
Yes, but it seems to be corrupt somehow. I use the EPG data for Jellyfin. The self generated XML file can be imported without problems whereas the XML downloaded from TV7_EPG_Data won't import.

I didn't dig deeper and inspected the content of the files, but the self generated file is much bigger than the file from here.
```
47416 -rw-r--r--  1 jellyfin jellyfin 48547754 May 31 09:00 tv7_epg.xml.generated
23452 -rw-r--r--  1 jellyfin jellyfin 24011756 May 31 08:48 tv7_epg.xml.data
```

**Comment by brknkfr** [comment]
How embarassing ... My bad, apparently the channels weren't discovered correctly on Jellyfin, so matching the EPG data with the corresponding channels didn't work, that's why importing didn't work on the first hand.

Even though, there is a difference between those two files (self generated and downloaded). Should it be this way or are those two files generated differently?

**Comment by mathewmeconry** [comment]
I improved the error handling with this commit reducing the problem where we don't have any data
https://github.com/mathewmeconry/TV7_EPG_Parser/commit/66b6118be2a0254001430ae95ff3f7cb2572f6c9

The size can differ because till this commit if one of the downloads failed the whole step (there are 2 of them = past and future) failed and no data will be present.

**Comment by mathewmeconry** [comment]
I guess it worked properly for the past few weeks. closing this
